import '../../global.css';
import 'react-loading-skeleton/dist/skeleton.css';
import { dir } from 'i18next';
import { Header } from '@front-main/widgets/header';
import { ApolloWrapper } from '@front-main/shared/api/graphql/apollo-wrapper';
import { LocaleProvider } from '@front-main/shared/model/i18n/locale-context';
import { languages } from '@front-main/shared/model/i18n/settings';

export const metadata = {
  title: 'Welcome to bar-map-frontend',
  description: 'Generated by create-nx-workspace',
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}) {
  return (
    <html lang={lang}>
      <body>
        <LocaleProvider value={{ lang: lang }}>
          <ApolloWrapper>
            <Header language={lang} />
            {children}
          </ApolloWrapper>
        </LocaleProvider>
      </body>
    </html>
  );
}
