import '../global.css';
import 'react-loading-skeleton/dist/skeleton.css';
import { ApolloWrapper } from '@front-main/shared/api/graphql/apollo-wrapper';

export const metadata = {
  title: 'Welcome to bar-map-frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
