services:
  db:
    restart: always
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: "bar_db"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - bar-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

volumes:
  bar-db-data:
